### ISSUE TITLE
Prepare new release v0.7

### ISSUE THREAD

**Issue by peter-szrnka** [peter-szrnka/firebase-hosting-api-java#29]
Add a new GitHub Action to manually release a new version.

**Comment by szrnka-peter** [comment]
Configure the release processing with

https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-maven

**Comment by peter-szrnka** [comment]
Try to use this GitHub Action:
https://github.com/marketplace/actions/java-maven-release

**Comment by peter-szrnka** [comment]
Subtask 2: fix the URLs and references in the pom.xml file
