### ISSUE TITLE
Cannot deserialize instance of `java.lang.String` out of START_ARRAY token I keep getting errors no matter the serializer i use

### ISSUE THREAD

**Issue by Greatcallie** [peter-szrnka/firebase-hosting-api-java#32]
I keep getting errors no matter the serializer i use.
Cannot deserialize instance of `java.lang.String` out of START_ARRAY token
 at [Source: (StringReader); line: 9, column: 24] (through reference chain: io.github.szrnkapeter.firebase.hosting.model.GetReleasesResponse["releases"]->java.util.ArrayList[0]->io.github.szrnkapeter.firebase.hosting.model.Release["version"]->io.github.szrnkapeter.firebase.hosting.model.Version["config"]->java.util.LinkedHashMap["redirects"])

**Comment by Greatcallie** [comment]
I managed to get passed that by changing the model objects. But i still get stuck with authentication : google.firebase.hosting.v1beta1.MetadataService.GetVersion, getting unauthorised.

**Comment by peter-szrnka** [comment]
Hi @Greatcallie !

Please provide more info about the issue:
- used version,
- sample code (without sensitive data),
- used serializer + source code,
- log details

Thanks,
Peter

**Comment by Greatcallie** [comment]
try {
            FileInputStream serviceAccount = new FileInputStream("firebase-adminsdk.json");

            FirebaseHostingApiConfig config = FirebaseHostingApiConfigBuilder.builder()
                    .withConfigStream(serviceAccount)
                    .withDefaultConnectionTimeout(90000)
                    .withDefaultReadTimeout(90000).withSiteName("site-name").withCustomSerializer(new GsonSerializer())
                    .build();
            FirebaseHostingApiClient client = new FirebaseHostingApiClient(config);
            DeployRequest request = new DeployRequest();
            request.setCleanDeploy(false);
            DeployItem di1 = new DeployItem();
            di1.setName("rates.json");
            di1.setContent(Files.readAllBytes(new File("rates.json").toPath()));
            Set<DeployItem> fileList = new HashSet<>();
            fileList.add(di1);
            request.setFiles(fileList);
            DeployResponse response = client.createDeploy(request);
            System.out.println("response is " + response);
        } catch (Exception e) {
            System.out.println("error is: " + e.getLocalizedMessage());
        }
public class GsonSerializer implements Serializer {

    private final Gson gson;

    public GsonSerializer() {
        this.gson = new Gson();
    }

    @Override
    public <T> T getObject(Class<T> clazz, String json) {
        return gson.fromJson(json, clazz);
    }

    @Override
    public <T> String toJson(Class<T> clazz, T obj) {
        return gson.toJson(obj);
    }
}
{
  "error": {
    "code": 401,
    "message": "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "status": "UNAUTHENTICATED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "CREDENTIALS_MISSING",
        "domain": "googleapis.com",
        "metadata": {
          "service": "firebasehosting.googleapis.com",
          "method": "google.firebase.hosting.v1beta1.MetadataService.GetVersion"
        }
      }
    ]
  }
}

**Comment by Greatcallie** [comment]
oh and i used the latest version - 0.6. Thanks

**Comment by peter-szrnka** [comment]
Based on the error message and the JSON  file, the issue is possibly with your firebase config file, it does not look valid for me. A valid config file contains client info, oauth credentials, project info, etc.

Sample description:
https://docs.edna.io/kb/downloading-google-services-json-file-from-firebase/

**Comment by Greatcallie** [comment]
"type": "service_account",
  "project_id": "",
  "private_key_id": "",
  "private_key": "---END PRIVATE KEY-----\n",
  "client_email": "firebase-a",
  "client_id": "",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url

mine looks like this. And it works for other authentication needs.

**Comment by Greatcallie** [comment]
Also omitting withSiteName(), cuts it off early with unauthenticated error.
{
  "error": {
    "code": 401,
    "message": "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "status": "UNAUTHENTICATED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "CREDENTIALS_MISSING",
        "domain": "googleapis.com",
        "metadata": {
          "service": "firebasehosting.googleapis.com",
          "method": "google.firebase.hosting.v1beta1.MetadataService.ListReleases"
        }
      }
    ]
  }
}

**Comment by peter-szrnka** [comment]
I'm sure there's a permission issue with your service account. I've tested with a dummy, Maven based project, without any deployable file:

![image](https://github.com/peter-szrnka/firebase-hosting-api-java/assets/8747465/4021aec8-1a92-489b-9ee6-c80f83a73edb)


`

public class Main {
    
    public static void main(String[] args) {
        System.out.println("Start");

		InputStream apiSdkStream = Main.class.getClassLoader().getResourceAsStream("sdk.json");

        FirebaseHostingApiConfigBuilder firebaseRestApiConfigBuilder = FirebaseHostingApiConfigBuilder.builder() //
				.withDefaultConnectionTimeout(90000) //
				.withDefaultReadTimeout(90000) //
				.withConfigStream(apiSdkStream) //
				.withCustomSerializer(new GsonSerializer()) //
				.withServiceResponseListener(new ServiceResponseListener() {
					@Override
					public <T> void getResponse(String function, T response) {
						System.out.println(function + " / " + response);
					}
				})
				.withSiteName("site-name");
	
		FirebaseHostingApiConfig firebaseRestApiConfig = firebaseRestApiConfigBuilder.build();

		try {
			FirebaseHostingApiClient client = new FirebaseHostingApiClient(firebaseRestApiConfig);

			DeployRequest deployRequest = new DeployRequest();
			deployRequest.setCleanDeploy(false);
			deployRequest.setDeletePreviousVersions(true);
			Set<DeployItem> files = new HashSet<>();
			deployRequest.setFiles(files);
			client.createDeploy(deployRequest);
		} catch (Exception e) {
			e.printStackTrace();
		}
    }
}
`

and it didn't throw any authentication/authorization error, only HTTP 400 (because of incomplete request).
![image](https://github.com/peter-szrnka/firebase-hosting-api-java/assets/8747465/0396f7bf-d1c1-430b-9e1b-e28d1060481a)


 I've generated a new key for that:
![image](https://github.com/peter-szrnka/firebase-hosting-api-java/assets/8747465/470b87d1-00d2-4a60-9b0a-00b8399df908)

**Comment by Greatcallie** [comment]
That's the 400 error, its the same thing. when you open it you will see the authentication error. I actually want it to work.

**Comment by peter-szrnka** [comment]
You had 401's, not 400. They are not the same. As you can see in my log messages, there was 1 successful sub service call (create version) before the failed sub process, so the authentication was successful.

**Comment by Greatcallie** [comment]
Trust me its the same with me i just pasted the contents of the 400 link. You didn't paste your own content. Pls paste the content of the link in the error message. I have also stated that some requests were successful earlier.

**Comment by peter-szrnka** [comment]
I have an ongoing, daily running project with v0.6 for more than 2 years without any failure, that's why it's strange.

I'll check it further after my PTO. :)

**Comment by Greatcallie** [comment]
you could easily add a txt file to the server with this and its not going to affect your running project. Unless this is a dummy project.

**Comment by peter-szrnka** [comment]
Version 0.7 release to Maven Central:
- siteName renamed to siteId
- configStream renamed to ServiceAccountFileStream
- Additional validations added

Additionally:
- Sample, working projects created for:
	- v0.6 -> https://github.com/peter-szrnka/firebase-hosting-api-java/tree/main/examples/version_0.6
	- v0.7 -> https://github.com/peter-szrnka/firebase-hosting-api-java/tree/main/examples/version_0.7
- Detailed guide created for Firebase project configuration: https://github.com/peter-szrnka/firebase-hosting-api-java/blob/main/FIREBASE_SETUP.md
- README.md file updated

Minor notes:
- httpResponseListener and serviceResponseListener parameters are optional, and it does not mean that the application will not work if these parameters missing, only the logs will be hidden and unavailable.
